/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminUserDetail: typeof import('./src/components/AdminUserDetail.vue')['default']
    ChangePassword: typeof import('./src/components/ChangePassword.vue')['default']
    CreateDepositoForm: typeof import('./src/components/CreateDepositoForm.vue')['default']
    DepositoList: typeof import('./src/components/DepositoList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HistoryMutasi: typeof import('./src/components/HistoryMutasi.vue')['default']
    InputForm: typeof import('./src/components/InputForm.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MyDeposito: typeof import('./src/components/MyDeposito.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProfileForm: typeof import('./src/components/ProfileForm.vue')['default']
    RekapList: typeof import('./src/components/RekapList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpForm: typeof import('./src/components/SignUpForm.vue')['default']
    TransactionHistory: typeof import('./src/components/TransactionHistory.vue')['default']
  }
}
